[package]
name = "himitsu"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
# For Tests
# toml = "0.5.8"
# serde = { version = "1.0.136", features = ["derive"] }

[dependencies]
thiserror = "1.0.30"
crossbeam = "0.8.1"